name: Deploy db

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DATABASE_USER: doadmin

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up DigitalOcean
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_TOKEN_ACCESS }}


      - name: Retrieve database URI and user's password
        run: |
          MONGO_DB_ID=$(doctl db list | grep mongo | awk '{print $1}')
          RAW_DB_URI=$(doctl db connection $MONGO_DB_ID --format URI --no-header)
          echo $RAW_DB_URI
          DB_URI=$(echo "$RAW_DB_URI" | sed 's|mongodb+srv://|mongodb://|')
          echo "DB_URI=$DB_URI" >> $GITHUB_ENV
          DB_PASS=$(doctl databases user get $MONGO_DB_ID doadmin --format Password --no-header)
          echo "DB_PASS=$DB_PASS" >> $GITHUB_ENV

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: run gradle
        env:
          DATABASE_URL: ${{ env.DB_URI }}
        run: |
          sed 's/#DB_PASS#/'"$DATABASE_PASSWORD"'/g' -i .env
          sed 's/#DB_URI#/'"$DATABASE_URL"'/g' -i .env
          ./gradlew --no-daemon update
